Repository opendatasoft/ods-dataviz-sdk, pull requests merged in 2023-09, with the labels that each got.

#189 [sc-43517] Expose config for Bar and Column charts with groups
  packages/visualizations-react/stories/Chart/AxisAssemblages/AxisAssemblages.stories.tsx
  packages/visualizations/src/components/Chart/datasets.ts
  packages/visualizations/src/components/Chart/types.ts
Labels: enhancement, packages/visualization

#182 [FEATURE][SC-42061] Add scatter chart
  packages/visualizations-react/stories/Chart/AxisAssemblages/AxisAssemblages.stories.tsx
  packages/visualizations/src/components/Chart/Chart.svelte
  packages/visualizations/src/components/Chart/datasets.ts
  packages/visualizations/src/components/Chart/scales.ts
  packages/visualizations/src/components/Chart/types.ts
Labels: enhancement

#193 fix: Use same typing for `indexAxis` as other charts series
  packages/visualizations-react/stories/Chart/AxisAssemblages/AxisAssemblages.stories.tsx
  packages/visualizations/src/components/Chart/datasets.ts
  packages/visualizations/src/components/Chart/types.ts
Labels: bug
